### ISSUE TITLE
Add project path to BackTraceLine's file to get the github backtrace links to work

### ISSUE THREAD

**Issue by mmcdaris** [airbrake/airbrake-java#30]
The github integration does not work as expected because we need to have a full project path to build the github links in the file attribute of the [BackTraceLine.java](https://github.com/airbrake/airbrake-java/blob/master/src/main/java/airbrake/BacktraceLine.java#L43):43
here is an example backtrace reported by the [airbrake-ruby notifier](https://github.com/airbrake/airbrake) that leads to the corresponding file in github ( based off json response from the api that is used in airbrake.io ):

```
column: 0
file: "[PROJECT_ROOT]/lib/integrations/foo/bar.rb"
function: "rescue in notify"
line: 13
```

airbrake-java would miss the project path inclusion and report this one as:

```
column: 0
file: "bar.rb"
function: "rescue in notify"
line: 13
```

**Note:** please excuse the .rb extensions as they are purely for comparison
After this change is made the airbrake-java notifier will be providing the necessary information to get the most out of the github integration.
As a user you can click through from backtrace to file in github

_Happy to explain in further details anything stated above._

**Comment by bradical** [comment]
We ran into a similar issue but it appears in our case that both the PROJECT_ROOT as well as the classpath paths are missing from the backtrace #46 so Airbrake is always looking for our classes -- regardless of their classpath -- at the room of our project: `http://github.com/org/project/Class.java`.

**Comment by vmihailenco** [comment]
Answered in https://github.com/airbrake/airbrake-java/issues/46
