### ISSUE TITLE
Airbrake doesnt log messages with level INFO , WARNING, DEBUG

### ISSUE THREAD

**Issue by dbakore** [airbrake/airbrake-java#33]
I have configured Airbrake using Log4j within our Java Application. To do so I followed the instructions listed in your documentation:
https://help.airbrake.io/kb/installing-airbrake-in-your-application...

It is working and I can see all the exceptions logged within the air brake Dashboard. However I do not see log messages under levels "INFO" , "DEBUG" and "WARNING" within the dashboard. The only messages I see is ERROR. The Log level within the application is set to "INFO" and its logging all messages in stdout.

Is there any specific setting that I need to do in Log4j properties or our application to make this work?

**Comment by vmihailenco** [comment]
You need to set log4j appender threshold

```
log4j.appender.AirbrakeAppender.Threshold=debug
```
