### ISSUE TITLE
Incorrect XML Escaping

### ISSUE THREAD

**Issue by kohenkatz** [airbrake/airbrake-java#37]
Similar to #25 and #22, but with a different cause.

One line in our backtrace looks like this:

```
<line method="Caused by service.getName" file=") "Tomcat"; Protocol handler start failed" number="-1"/>
```

The unescaped quotes are causing a syntax error.

**Comment by johnmcconnell** [comment]
Same here @lucamarrocco

**Comment by alexmreis** [comment]
+1. I'm trying to write a patch to fix this but their unit tests are broken... :)

**Comment by johnmcconnell** [comment]
If their unit tests don't work then don't worry about it.

Just make sure what you write is correct.

And remember the unit tests are supposed to work **for you**, not the other way around.

**Comment by alexmreis** [comment]
Thanks for the encouragement @johnmcconnell. Fixed it on #52, hope they accept and release soon, it seems the java client was left behind, it doesn't even use the JSON API yet.

**Comment by johnmcconnell** [comment]
@alexmreis I'll take a look at your MR. I don't the have the authority to merge, but I can check for errors.

**Comment by vmihailenco** [comment]
Should be fixed in https://github.com/airbrake/javabrake
