### ISSUE TITLE
Airbrake agent

### ISSUE THREAD

**Issue by miere** [airbrake/airbrake-java#40]
I'm using this client for a week and I'm very glad with the airbrake.io at all. It is quite useful and is providing me important insights.

I was wondering if an "Airbrake java agent" wouldn't be a more agnostic approach. What do you maintainers think about it?

Here what I have in mind:
- Make the airbrake-java a complete standalone module, without Log4J dependency.
- Create a airbrake-log4j to provide backward compatibility.
- Create a Java Agent that inspects every thrown exception and send data to Airbrake.io.

Let me know what do you guys think about it. I could help with the agent if you guys think this is useful.

Regards

**Comment by vmihailenco** [comment]
This never happened and there is now https://github.com/airbrake/javabrake. Closing.
