### ISSUE TITLE
AirbrakeAppender should not keep lock while waiting for response from remote server

### ISSUE THREAD

**Issue by albin-pawel** [airbrake/airbrake-java#41]
Hi 

Today we notice huge issue on our production servers. We spend two days to analize it and we found out that AirbrakeAppender holds lock in org.apache.log4j.Category.callAppenders(Category.java:205). We are using log4j 1.2.16 and it cannot be updated, so until its fixed we have to disable Airbrake on all our systems

**Comment by vmihailenco** [comment]
Hopefully fixed in https://github.com/airbrake/javabrake
