### ISSUE TITLE
Backtrace list is empty when exception contains empty message

### ISSUE THREAD

**Issue by spatail** [airbrake/airbrake-java#43]
Any exception thrown with an empty message, e.g. `new RuntimeException("")`, leads to the _Backtrace.**filteredBacktrace**_ being an empty list. This is because the regex on the following line in _Backtrace_:
`ignore(".*" + Pattern.quote(messageIn(throwable)) + ".*");`
turns into `.*\Q\E.*`
During Backtrace iteration, this regex will filter out all the lines causing the notice to be generated with `<backtrace />`.

The fix is actually pretty simple. We just need to update the following line in _Backtrace.**messageIn**_
`if (message == null) {`
to
`if (message == null || message.equals("")) {`

I would be happy to submit a PR :)

**Comment by vmihailenco** [comment]
Hopefully fixed in https://github.com/airbrake/javabrake
