### ISSUE TITLE
Mapping Java classes in backtrace to location in repository project with airbrake-java-2.2.8.jar and log4j

### ISSUE THREAD

**Issue by bradical** [airbrake/airbrake-java#46]
We use the Java version of the Airbrake Notifier and it generally works very well. Though, one thing I've noticed is that the backlinks to the classes in the project never seem to work b/c it doesn't seem like there is enough information there to be able to correctly link to the right classes in my project.

Here's an example:

```
AbstractLazyInitializer.java:57 in org.hibernate.proxy.AbstractLazyInitializer.initialize
AbstractLazyInitializer.java:111 in org.hibernate.proxy.AbstractLazyInitializer.getImplementation
CGLIBLazyInitializer.java:150 in org.hibernate.proxy.pojo.cglib.CGLIBLazyInitializer.invoke
<generated>-1):-1 in com.hannonhill.cascade.model.dom.StructuredDataDefinition$$EnhancerByCGLIB$$cb2554ad.getXml
Page.java:306 in com.hannonhill.cascade.model.dom.Page.createSpoofedStructuredData
Page.java:330 in com.hannonhill.cascade.model.dom.Page.migratePageXHTML
Page.java:347 in com.hannonhill.cascade.model.dom.Page.getStructuredData
```

With the links to our Page class, the problems seems to be that Airbrake doesn't know that my Page class resides at: `src/java/com/hannonhill/cascade/model/dom/Page`. So the links always like like this:

```
https://github.com/org/project/<revision>/<class_name>.java
```

Is there something I need to be doing in my deploys or otherwise to let Airbrake know where in my project tree my classes are located?

Thanks!

**Comment by vmihailenco** [comment]
Moving this https://github.com/airbrake/javabrake, but real location of the file is lost during compilation and I don't any way to recover it without help from the user.
